config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :trn_news do 
    resources :trn_comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :trn_users, controllers: {
    sessions: "trn_users/sessions",
    registrations: "trn_users/registrations"
  }
  # Defines the root path route ("/")
  root "trn_news#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand"  do %>
      <p class="m-auto nav-title">The Rial News </p>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if trn_user_signed_in? %>
                <% if current_trn_user.name %>
                Hola <%= current_trn_user.name %>
              <% else %>
                Hola <%= current_trn_user.email %>
              <% end %>
            <% else %>
                Inicia sesión o regístrate
            <% end %>
          </a>
          <ul class="dropdown-menu ms-auto">
            <% if trn_user_signed_in? %>
              <li><%= button_to "Cerrar Sesión", destroy_trn_user_session_path, class:"dropdown-item", method: :delete %></li>
            <% else %>
              <li><%= link_to "Iniciar Sesión", new_trn_user_session_path, class:"dropdown-item" %></li>
              <li><%= link_to "Registro", new_trn_user_registration_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>