config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :trn_news do 
    resources :trn_comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :trn_users, controllers: {
    sessions: "trn_users/sessions",
    registrations: "trn_users/registrations"
  }
  # Defines the root path route ("/")
  root "trn_news#index"
end

app/models/trn_comment.rb
class TrnComment < ApplicationRecord
  belongs_to :trn_user
  belongs_to :trn_new
end

app/controllers/trn_comments_controller.rb
class TrnCommentsController < ApplicationController
  before_action :set_trn_comment, only: %i[ show edit update destroy ]
  before_action only: [:new, :create] do
    authorize_request(["trn_normal_user", "trn_admin"])
  end
  before_action only: [:destroy] do
    authorize_request(["trn_admin"])
  end

  # GET /trn_comments or /trn_comments.json
  def index
    @trn_new = TrnNew.find(params[:trn_new_id])
    @trn_comments = TrnComment.all
  end

  # GET /trn_comments/1 or /trn_comments/1.json
  def show
    @trn_new = TrnNew.find(params[:trn_new_id])
    @trn_comment = @trn_new.trn_comments.find(params[:id])
  end

  # GET /trn_comments/new
  def new
    @trn_new = TrnNew.find(params[:trn_new_id])
    @trn_comment = TrnComment.new

  end

  # GET /trn_comments/1/edit
  def edit
  end

  # POST /trn_comments or /trn_comments.json
  def create
    @trn_new = TrnNew.find(params[:trn_new_id])
    @trn_comment = @trn_new.trn_comments.build(trn_comment_params)
    @trn_comment.trn_user = current_trn_user

    respond_to do |format|
      if @trn_comment.save
        format.html { redirect_to trn_new_path(@trn_new), notice: "CSomment was successfully created." }
        format.json { render :show, status: :created, location: @trn_comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trn_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trn_comments/1 or /trn_comments/1.json
  def update
    respond_to do |format|
      if @trn_comment.update(trn_comment_params)
        format.html { redirect_to trn_comment_url(@trn_comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @trn_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trn_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trn_comments/1 or /trn_comments/1.json
  def destroy
    @trn_new = TrnNew.find(params[:trn_new_id])
    @trn_comment = @trn_new.trn_comments.find(params[:id])
    @trn_comment.destroy

    respond_to do |format|
      format.html { redirect_to trn_new_path(@trn_new), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trn_comment
      @trn_comment = TrnComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trn_comment_params
      params.require(:trn_comment).permit(:content, :trn_user_id, :trn_new_id)
    end
end

app/helpers/trn_comments_helper.rb
module TrnCommentsHelper
end

app/views/trn_comments/_form.html.erb
<%= form_with(model: @trn_comment, url: trn_new_trn_comments_path(@trn_new), method: :post) do |form| %>
  
  <% if trn_comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trn_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% trn_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row d-flex justify-content-center comment">
      <div class="col-md-8 col-lg-6 mb-5">
        <div class="card shadow-0 border">
          <div class="card-body p-0">
            <div class="card m-0">
              <div class="card-body">
               

              
                  <div class="d-flex flex-row align-items-center">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(4).webp" alt="avatar" width="100"  height="100"
                      height="25" />
                     <div class="comment-content ms-2">
                        <%= form.text_area :content, class:"comment-content" %>
                      </div>
                  </div>

              </div>
            </div>
            </div>
          </div>

          <div class="text-center mt-2">
            <%= form.submit  "Guardar comentario", class:"btn btn-dark news-title" %>
          </div>

        </div>
      </div>
      
    </div>
    

<% end %>

app/views/trn_comments/_trn_comment.html.erb
<%= link_to  trn_new_trn_comment_path(@trn_new, trn_comment) do %>
    <div id="<%= dom_id trn_comment %>">

    <div class="row d-flex justify-content-center comment">
      <div class="col-md-8 col-lg-6 mb-5">
        <div class="card shadow-0 border">
          <div class="card-body p-0">
            <div class="card m-0">
              <div class="card-body">
                <p><%= trn_comment.content %></p>

                <div class="d-flex justify-content-between">
                  <div class="d-flex flex-row align-items-center">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(4).webp" alt="avatar" width="25"
                      height="25" />
                    <p class="small mb-0 ms-2"><%= trn_comment.trn_user.name %></p>
                  </div>
                  <div class="d-flex flex-row align-items-center">
                    <p class="small text-muted mb-0 me-2">Upvote?</p>
                    <i class="bi bi-hand-thumbs-up"></i>
                    <p class="small text-muted mb-0">3</p>
                  </div>
                </div>
              </div>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end%>

app/views/trn_comments/edit.html.erb
<h1>Editing trn comment</h1>

<%= render "form", trn_comment: @trn_comment %>

<br>

<div>
  <%= link_to "Show this trn comment", @trn_comment %> |
  <%= link_to "Back to trn comments", trn_comments_path %>
</div>

app/views/trn_comments/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="text-center">
  <h1>Comments</h1>
</div>

<div id="trn_comments">
  <% @trn_comments.each do |trn_comment| %>
    <%= render trn_comment %>
  <% end %>
</div>

app/views/trn_comments/new.html.erb
 <div class="container mt-5">
  <%= link_to trn_new_path(@trn_new), class: "mt-auto  btn btn-dark news-title" do %>
        <div class="d-flex">
            <p class="m-auto me-3">Back to article</p><i class="bi bi-chevron-left"></i></i>
        </div>
    <%end %>
  <hr>  
  </div>

  
<div class= "container mt-5">
  <h4 class= "section-title text-center">New Comment</h4>
  <%= render "form", trn_comment: @trn_comment %>
  
</div>



   

app/views/trn_comments/show.html.erb
<p style="color: green"><%= notice %></p>
  <%= render @trn_comment %>
<div class=" container justify-content-center d-flex mt-5">

    <%= link_to trn_new_path(@trn_new), class: "mt-auto btn btn-primary ms-5 " do %>
      <p class="mt-1 ms-2">Back to new</p>
    <%end %>

  <!-- Mostrar botón para borrar comentario sólo si es Admin -->
    <% if trn_user_signed_in? %>
      <% if current_trn_user && current_trn_user.role?("trn_admin") %>
        <%= button_to trn_new_trn_comment_path(@trn_new, @trn_comment), method: :delete, class: "mt-auto ms-5 btn btn-primary" do %>
          <p class="mt-1 ms-2">Delete comment</p>
        <% end%>
      <%end %>
    <% end %>
   
</div>