config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :trn_news do 
    resources :trn_comments
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :trn_users, controllers: {
    sessions: "trn_users/sessions",
    registrations: "trn_users/registrations"
  }
  # Defines the root path route ("/")
  root "trn_news#index"
end

app/models/trn_new.rb
class TrnNew < ApplicationRecord

    has_many :trn_comments
end

app/controllers/trn_news_controller.rb
class TrnNewsController < ApplicationController
  before_action :set_trn_new, only: %i[ show edit update destroy ]
  before_action :authenticate_trn_user!, except: %i[ index show ]
  

  # GET /trn_news or /trn_news.json
  def index
    @trn_news = TrnNew.all
  end

  # GET /trn_news/1 or /trn_news/1.json
  def show
    @trn_new = TrnNew.find(params[:id])
    @trn_comments = @trn_new.trn_comments
  end

  # GET /trn_news/new
  def new
    @trn_new = TrnNew.new
  end

  # GET /trn_news/1/edit
  def edit
  end

  # POST /trn_news or /trn_news.json
  def create
    @trn_new = TrnNew.new(trn_new_params)

    respond_to do |format|
      if @trn_new.save
        format.html { redirect_to trn_new_url(@trn_new), notice: "Trn new was successfully created." }
        format.json { render :show, status: :created, location: @trn_new }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trn_new.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trn_news/1 or /trn_news/1.json
  def update
    respond_to do |format|
      if @trn_new.update(trn_new_params)
        format.html { redirect_to trn_new_url(@trn_new), notice: "Trn new was successfully updated." }
        format.json { render :show, status: :ok, location: @trn_new }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trn_new.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trn_news/1 or /trn_news/1.json
  def destroy
    @trn_new.destroy

    respond_to do |format|
      format.html { redirect_to trn_news_url, notice: "Trn new was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trn_new
      @trn_new = TrnNew.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trn_new_params
      params.require(:trn_new).permit(:image, :title, :description)
    end
end

app/helpers/trn_news_helper.rb
module TrnNewsHelper
end

app/views/trn_news/_form.html.erb
<%= form_with(model: trn_new) do |form| %>
  <% if trn_new.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trn_new.errors.count, "error") %> prohibited this trn_new from being saved:</h2>

      <ul>
        <% trn_new.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trn_news/_trn_index_new.erb
<!-- Parcial para la vista index -->



<div id="<%= dom_id trn_new %>">
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 d-flex justify-content-center right-bck">
            <div class="registration-right p-0">
                <div class="event-list">
                    <div class="card flex-row"><%= image_tag "#{trn_new.image}", class:"card-img-top" %>
                        <div class="card-body">
                             <h3 class="news-title"><%= trn_new.title %><h3>
                             <h4 class="card-title h5 h4-sm"><i class="fas fa-caret-right" aria-hidden="true"></i><span><%= trn_new.created_at %></span><i class="fas fa-caret-right" aria-hidden="true"></i></h4>
                        </div>
                            
                        <%= link_to trn_new, class: "mt-auto news-link" do %>
                            <p class="mt-1 ms-2">Read More</p>
                        <%end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/trn_news/_trn_new.html.erb
<div id="<%= dom_id trn_new %>">

<div class="container">

    <div class= "col-md-8 news-title m-auto mb-5">
      <%= link_to trn_news_path, class: "mt-auto btn btn-dark" do %>
        <div class="d-flex">
          <p class="m-auto me-3">Back to news index</p><i class="bi bi-chevron-left"></i></i>
        </div>
      <%end %>
      <hr>
      <h3 class="news-title mt-5"><%= trn_new.title %></h3>
    </div>
      

      
    <div class="col-md-10 m-auto">
      <%= image_tag "#{trn_new.image}", class:"news-img" %>
    </div>

      
    <div class= "col-md-8 news-body m-auto mt-5">
      <%= trn_new.description %>
    </div>
</div>
        
      
</div>

app/views/trn_news/edit.html.erb
<h1>Editing trn new</h1>

<%= render "form", trn_new: @trn_new %>

<br>

<div>
  <%= link_to "Show this trn new", @trn_new %> |
  <%= link_to "Back to trn news", trn_news_path %>
</div>

app/views/trn_news/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="section-title text-center mt-5">News</h1>

<div id="trn_news">
  <% @trn_news.each do |trn_new| %>
    <div class="mt-5 mb-5">
      <%= render 'trn_index_new', trn_new: trn_new %>
    </div>
  <% end %>
</div>

app/views/trn_news/new.html.erb
<h1>New trn new</h1>

<%= render "form", trn_new: @trn_new %>

<br>

<div>
  <%= link_to "Back to trn news", trn_news_path %>
  
</div>

app/views/trn_news/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="mt-5 mb-5">
  <%= render @trn_new %>
</div>

<div class=" container justify-content-center d-flex mt-3 mb-5">



</div>

<div id="trn_comments">
  <div class=" text-center mb-5">
    <h2 class="section-title">Comments</h2>
  </div>

  <% @trn_comments.each do |trn_comment| %>
    <%= render trn_comment %>
  <% end %>

  <!--Verificar si el usuario está logeado para que aparezca el botón-->
  <% if trn_user_signed_in? %>
    <% if current_trn_user.role %>
    <div class="text-center mt-5 mb-5 news-title">
      <%= link_to new_trn_new_trn_comment_path(@trn_new), class: "mt-auto btn btn-dark" do %>
        <div class="d-flex">
          <p class="m-auto me-3">Leave a comment</p><i class="bi bi-chat"></i>
        </div>
      <%end %>
    </div>
    <% end %>
  <% end%>
  
  
</div>